Repository ucsb-cs156-f24/proj-dining-f24-16, pull requests merged in 2024-11, with the labels that each got.

#42 Created a UCSBDiningMenuService that gets meal times and a controller endpoint that uses that service
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuController.java
  src/main/java/edu/ucsb/cs156/dining/services/UCSBDiningMenuService.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/UCSBDiningMenuServiceTests.java
Labels: 10

#45 Epic 3 Backend 2: Created a service and controller that uses it which returns the items on the menu
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
  src/main/java/edu/ucsb/cs156/dining/models/Entree.java
  src/main/java/edu/ucsb/cs156/dining/services/UCSBDiningMenuItemsService.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/UCSBDiningMenuItemsServiceTests.java
Labels: 10, Ready-For-Staff

#43 sa - added placeholder index page for myreviews and tested
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/MyReviews/MyReviewsIndexPage.js
  frontend/src/tests/pages/MyReviews/MyReviewsIndexPage.test.js
Labels: 5, Merge Candidate-CI

#34 Created the Entity for the Review table
  .gitignore
  src/main/java/edu/ucsb/cs156/dining/entities/Review.java
  src/main/java/edu/ucsb/cs156/dining/repositories/ReviewRepository.java
  src/main/resources/db/migration/changes/Reviews.json
Labels: 5

#49 Created Review Fixtures with review instances.
  frontend/src/fixtures/reviewFixtures.js
Labels: 5, Merge Candidate-CI

#56 created database for menu items
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
  src/main/java/edu/ucsb/cs156/dining/entities/MenuItem.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemRepository.java
  src/main/resources/db/migration/changes/MenuItem.json
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsControllerTests.java
Labels: 20, Merge Candidate-CI

#53 Sa moderate placeholderpage
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Moderate.js
  frontend/src/tests/pages/Moderate.test.js
Labels: 5, Merge Candidate-CI

#51 UpdateAlias and Moderation for feature#2 Backend
  src/main/java/edu/ucsb/cs156/dining/controllers/UserInfoController.java
  src/main/java/edu/ucsb/cs156/dining/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/dining/entities/User.java
  src/main/java/edu/ucsb/cs156/dining/repositories/UserRepository.java
  src/main/resources/db/migration/changes/Users.json
  src/test/java/edu/ucsb/cs156/dining/controllers/UserInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UsersControllerTests.java
Labels: 10

#58 4th Epic - Backend 1 - DiningCommonsService API Implementation with Service, Controller, and Model for DiningCommons
  src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/models/DiningCommons.java
  src/main/java/edu/ucsb/cs156/dining/services/DiningCommonsService.java
  src/test/java/edu/ucsb/cs156/dining/controllers/DiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/dining/services/DiningCommonsServiceTests.java
Labels: F24, Epic 4, 10, Merge Candidate-CI

#52 Review controller post and get all
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/main/java/edu/ucsb/cs156/dining/entities/Review.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemRepository.java
  src/main/java/edu/ucsb/cs156/dining/repositories/ReviewRepository.java
  src/main/resources/db/migration/changes/Reviews.json
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#54 Implement User-Specific Review Retrieval Functionality
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
Labels: 10

#59 Created Meals table and a Meal Times Page
  frontend/src/App.js
  frontend/src/fixtures/mealFixtures.js
  frontend/src/main/components/Meal/MealTable.js
  frontend/src/main/pages/Meal/MealTimesPage.js
  frontend/src/stories/components/Meal/MealTable.stories.js
  frontend/src/stories/pages/Meal/MealTimesPage.stories.js
  frontend/src/tests/components/Meal/MealTable.test.js
  frontend/src/tests/pages/Meal/MealTimesPage.test.js
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuControllerTests.java
Labels: 10

#65 Epic #4 ; Frontend 1 - DiningCommons Table + Fixtures, Stories, and Tests Included
  frontend/src/fixtures/diningCommonsFixtures.js
  frontend/src/main/components/DiningCommons/DiningCommonsTable.js
  frontend/src/stories/components/DiningCommons/DiningCommons.stories.js
  frontend/src/tests/components/DiningCommons/DiningCommonsTable.test.js
Labels: F24, Epic 4, 10, Merge Candidate-CI, Ready-For-Staff
